apiVersion: v1 # 오브젝트 정의에 사용할 k8s API 버전. v1이 가장 안정화 된 버전.
kind: Service # 리소스 타입
metadata:
  name: ordering-service # 생성하려는 서비스 이름.
spec: # 리소스 동작 방식 및 추가 설정
  selector: # 서비스가 트래픽을 전달할 대상 pod를 선택하는 기준
    app: ordering-service # label이 config-service를 가진 pod를 찾음.
  ports:
    - protocol: TCP
      port: {{ .Values.port }} # 외부에서 트래픽을 받을 포트
      targetPort: {{ .Values.port }} # selector로 선택된 pod로 트래픽 전달 시 사용할 포트.
  type: ClusterIP # 서비스의 접근 방식, ClusterIP: 클러스터 내부에서만 접근할 수 있는 IP를 사용.
                  # Ingress 가 있으면 NodePort를 사용하여 외부에서 접속경로를 열 필요가 없음.

