# values.yml에 있는 services들을 순회하면서 각 서비스에 대한 Service 리소스를 일괄 생성.

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.messagingPort }}
      targetPort: {{ .Values.service.messagingPort }}
      protocol: TCP
    - name: management
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      protocol: TCP
  type: ClusterIP
