apiVersion: v2
name: umbrella-chart
description: Umbrella chart for deploying all services in the Spring Cloud MSA
type: application
version: 1.0.0
appVersion: 1.0.0

# Umbrella Chart의 하위 차트를 정의.(상위 차트 install할때 의존성 있는 나머지들도 함께 install 되도록)
dependencies:
  - name: rabbitmq
    version: 1.0.0
    repository: file://charts/rabbitmq
  - name: config-service
    version: 1.0.0
    repository: file://charts/config-service
  - name: user-service
    version: 1.0.0
    repository: file://charts/user-service
  - name: ordering-service
    version: 1.0.0
    repository: file://charts/ordering-service
  - name: product-service
    version: 1.0.0
    repository: file://charts/product-service
  - name: gateway-service
    version: 1.0.0
    repository: file://charts/gateway-service